### PR TITLE
Require modules only if needed

### PR DESCRIPTION
**Pull request by sbmaxx**

### CODE REVIEW

**Comment by tadatuta** [comment]
all tests failed with
```
 Error: Cannot find module 'postcss'
      at module.exports.buildFlow.create.name.target.defineOption.defineOption.defineOption.defineOption.defineOption.defineOption.defineOption.defineOption.defineOption.defineOption.useFileList.saveCache.needRebuild.builder.methods._processCss (techs/stylus.js:315:29)
      at null.<anonymous> (techs/stylus.js:122:29)
```

**Comment by sbmaxx** [comment]
@tadatuta fixed.

very strange mocks in tests

**Comment by blond** [comment]
@sbmaxx, squashed commits, please, and I'll merge.

**Comment by sbmaxx** [comment]
@blond done

**Comment by blond** [comment]
Thanks!

**Pull request merged**
